language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
  - node_modules

script:
  - env
  - yarn build

before_deploy:
  - yarn global add firebase-tools

deploy:
  - provider: firebase
    skip_cleanup: true
    project: fireroom-cohacking-challenge
    token:
      secure: xNtBv5DTJmilYrd1asZV/Nu1KXh78VbP1VVecVOTsQESnFYqA/ZIlDpO0Hs4iWnw2JyHSDcT9C9coX8Sk54KYPTDriBusTkegTe7cR5Gjl6nbPl7oHcQRbY/iipqRY6H+fEMy9U2R55nY2elIGO1vBAQNxtRFZpxKI/+BmLxYeDJaIhDtqj2Jz+eVvE08Eun2hKswAniQTYTh+8djH55lEh9RA9rVDUWyP30Zg5oEHuCt24SRpADWqV66+fvGwJUpNX4PvuQmKlKLLqdkiUabTJZuBHcHlrc9IosmZ020zgb0BM2tj9BnfhtJvCvmP3xf0yIJhxL9MtN8WcL2ygAcBmh0myBeuuNrmfd/uDNQKLF1+B6E9BUrD2ENkJSUWqm0j5q6EXmWWWd/hNl/RrZF+pQYRIZqjATZsO9aGU2Eotb5Ph0qx7Kh6QtuZUpb3yBvZtSY29mAC1WZFIH/Cny2JG1+SFzweDqQSd5xniAtpLCK3nDsqHAlddQoDOljKO4HNUQ6UXAa1qQZp4TwaFa81uJMqf0xvhhT4v/ViW3AXJOvK1giy1aTiTxemTz3LyT9VqXyP/quxwmzg5RvgxhEPgs0/gm4BOecP3iSuDgBRi/t3bnq1c/HwB5kRm+FXe3IiwO85CC8qB3W6/4fKdo4tbyKC/RBGdmTXUGrXWSgno=
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    project: fireroom-staging
    token:
      secure: xNtBv5DTJmilYrd1asZV/Nu1KXh78VbP1VVecVOTsQESnFYqA/ZIlDpO0Hs4iWnw2JyHSDcT9C9coX8Sk54KYPTDriBusTkegTe7cR5Gjl6nbPl7oHcQRbY/iipqRY6H+fEMy9U2R55nY2elIGO1vBAQNxtRFZpxKI/+BmLxYeDJaIhDtqj2Jz+eVvE08Eun2hKswAniQTYTh+8djH55lEh9RA9rVDUWyP30Zg5oEHuCt24SRpADWqV66+fvGwJUpNX4PvuQmKlKLLqdkiUabTJZuBHcHlrc9IosmZ020zgb0BM2tj9BnfhtJvCvmP3xf0yIJhxL9MtN8WcL2ygAcBmh0myBeuuNrmfd/uDNQKLF1+B6E9BUrD2ENkJSUWqm0j5q6EXmWWWd/hNl/RrZF+pQYRIZqjATZsO9aGU2Eotb5Ph0qx7Kh6QtuZUpb3yBvZtSY29mAC1WZFIH/Cny2JG1+SFzweDqQSd5xniAtpLCK3nDsqHAlddQoDOljKO4HNUQ6UXAa1qQZp4TwaFa81uJMqf0xvhhT4v/ViW3AXJOvK1giy1aTiTxemTz3LyT9VqXyP/quxwmzg5RvgxhEPgs0/gm4BOecP3iSuDgBRi/t3bnq1c/HwB5kRm+FXe3IiwO85CC8qB3W6/4fKdo4tbyKC/RBGdmTXUGrXWSgno=
    on:
      branch: staging

# For now it's only for staging
env:
  global:
  - secure: f98ejU5zGi1YqvJfNeOUdMrmg/AVGoMpIZ5jaqArg3mLjCaU6SDrdkvqRis1tPA4xZXZj0jHcJIAK+0qMKoYQF0cgWuYR3Lh58G+j1Sa9YXrVNOU0XEyNJpRZLVcbtxn5hVfOmo9ZbZuNbPo7MwgOwhxrTHRvTf4pFquvMvwItq4vAU/FXm/jPvxluGMp9cmZeSbD9OkX2PR1gijD3Wrvog+bjoLQTkYlZxJm0ufWx+qtnvRKcUDuT+KTzh8YlneAUaLYrNvi9vHbktQcxKimOBAzGwiEx6tLvU+fqPl9ubwUN6cdvxJ8jKB17TIs58Xpjf3F9eS8eD0wcs0k0cyMknKH9EmSxH0C6m4GoiygBjGsZq3AD9avV0sSkvvw371Ps+6uqABRY0rKFSCJsgLSDbgpO9Bid6zEHx5piAtwHG2A+jEXeHCbRHzyQZEgKA4LjOAhdnBRVYgDR+bXpGVIZQzcxlLOj01WAaWlOqeAK1+Df9cX+9JGvjJ4AtYdLLTNixX/nR6RdeyCC9neUDZwRcV6SUvfamP33KUi9g5/txtela5PpHFtoer8UPfSMJY7ebtYO9ufsUvxenfMyiL5R2cwjTth3NudchP2pTwnqGHwMk+mpalPI4RppSxU3EX5DhpithNweZOymxC0A5KpuEjTiPltHgPeiZQa+L4lJQ=
  - secure: S+nOPmQLSky0ldap1L07ZFvp9TU/xUL27mURvbuqWoNKcP9uj9tCrvEPbYNcBw5ww0YaiziOvTUIKoLvhjTI9x2GNfnFAA+b50ZryqVt0tYs3hrOG/afRkOkyhUNvz1xLo293Bh5AEV38JRTWGA4SQF7tvKwUo3Z9cCC69KrXjPxuNaPWX9NOSmsm8F4ienZSr7BPk/gGwR9GKk+I0dY3YUkuFEuV/GGFeV2cHBLHpmWU0azXA2609DCePkyeuqPpxi0h2fkuH6QrS7e/pCscUHHK6Y82FeQ1hCMqtvFkUGYzkzYXLHPzwjzsfi+N+KZQYZ0Po8csO5GIRMvXw2vPdNk+2Kssi6eFXYqqWKa3OT2mSUExXqr2D9YqIgXaIQt5nirSIvs5Bzj10mw/7UcGnHQNZeioOb4fzQeDU3+oa/ycOlcBh+4SMaD2rgpSjkBugWa1/gcGh1SR0RbgA0MH/VQllMlnYCMmM27XDsOwSqqdc60RB1Qz3csE2NXnj8XM5leaLhhl1sqs4CiTVitqhC/4egZoIIDUUHAfM89uUVVTdTZg3cc4n+hAIK2KLV4pPOY+bdV+C+UGUYRphBXl4F7sGV0i+OfHvh045iKlLhGmo1nyt6V1/JbP7KdqNXv9ffIYokgyjrkAehtvigu+zthONelrA3z1phcRx16J4c=
  - secure: NJyNBBVp8E4P6l2Lh0lperZq6F5LSJ9cDVitJtyAgkuytHX6B90kkfcQlYvGkcIg7PW0z5CgJsdKwFy5HmoNx9KXiaZuGnNqKHVy/vv9Wq3h1/vA37iLxr9Sw3UlLFzCpSvPNiPkvR7TAY/ZNPF2xiBBydejD9sp5MMQKGdnOLcglUkLAU9/G+6FGJRSjNFR+/HVlO+hRWtLtKY7rRsf3y2fDAX1ph7aLSu9wkOm2aifsQQ34Ku8L4xnMy2hz5rWmxknD+hxQWuaDaC8ItLafeSKBTOjiFZsaUlcxG6Hk1tlv8H44rIVqWsUcd6SacIh9QHn5cl50Otop7K07QKlTUtbZ9HjhIBiW0nymf7uRqHIczF1+t27e4JHgh3Eej85EN+tIe5U1fW4VveyAl4gMbKj0DMfwfLPRSJFBaR1XzOME9dxtI1qBuggCbni7yynqC275jI6xYpw99zpy+OQUjD98iWiUq0CTU3Evk+ASGhkkBB0W0uT2WK+EIUFGWrHsMjVw5ZtXXZ+yq14RET8WcqMLYbdW7O85QdtvkEkSrgTETKg3KHdF8eRTwrXdx7xpaq4ltmxfvV+vFMW9UrbpcuMwfYpgesAwU9bIz2/o97ckOYrJd/2qn6XjmMO5YWs5QSNf4m/M8Y0Xhu5gbLTcEdyVFz0kw5Us+NWsGDbxgM=
  - secure: hYo86tRS7WedCtJ5krduR8LjmC/Y5oh3hW3VS7cn1DO6nvOOgf7QU0QXiKUtk2grReOFm7VOGmVBYK0roTWEuJw3I6HuKIkVa98ItK+zg9JLHZvpIJrLpB4/AlZalsdWWrXduyOb+CNBUMBiZHu55T/gzcKGZznsdKz7PYRQY2FSJoCanT54LoovXELaJici+1tI5uewbCR0Jx3ePvIpLX/3ra3m6qFoZ/MEdabeZ3qkGJWmsnz1xFpRZxq65P71vWKV7v/DEeuZtj5ZJy/OAsj+OHQzuSCWJ4awgBkPXZlS/XtzTf9oPKqnAB2wvwMYBl9otL/YdrBMKyoZ/Oajya1UXLGvrhFb07FNQW+BsgfuGxRozNPxA0pC78u4xTfMkznAYvcyfPrhoXrLrFEE4jP4RpX7XoRX0NhWMQSnri6waozkdXK9Q1xBeBUJRiIkjau9PqiQKslcw4MzhOctc037Wo05Njhjdp/pJbsA8SPoXbl5CgVX/UnYLPsCU1wwYpb24Em8uVYlaOcAYoH9K9VClxb3EtbOE9lVDuFJ+Zs5mVrsIBKzFOBWP2oqyOUQWNwJ2CaVVpYaIpTLosz/0QQOFCuzhcCOTD8JMzklBwgfZduNy1wdTDM8GV6EVVjgJWN18CYyrFPJYvjQRdANUAry025SHS5L0Z8ULXVSPdY=
